/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PolitikaRouteImport } from './routes/politika'
import { Route as OfertaRouteImport } from './routes/oferta'
import { Route as DiagnostikaRouteImport } from './routes/diagnostika'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as IndexRouteImport } from './routes/index'

const PolitikaRoute = PolitikaRouteImport.update({
  id: '/politika',
  path: '/politika',
  getParentRoute: () => rootRouteImport,
} as any)
const OfertaRoute = OfertaRouteImport.update({
  id: '/oferta',
  path: '/oferta',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnostikaRoute = DiagnostikaRouteImport.update({
  id: '/diagnostika',
  path: '/diagnostika',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/diagnostika': typeof DiagnostikaRoute
  '/oferta': typeof OfertaRoute
  '/politika': typeof PolitikaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/diagnostika': typeof DiagnostikaRoute
  '/oferta': typeof OfertaRoute
  '/politika': typeof PolitikaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/diagnostika': typeof DiagnostikaRoute
  '/oferta': typeof OfertaRoute
  '/politika': typeof PolitikaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cookies' | '/diagnostika' | '/oferta' | '/politika'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cookies' | '/diagnostika' | '/oferta' | '/politika'
  id: '__root__' | '/' | '/cookies' | '/diagnostika' | '/oferta' | '/politika'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CookiesRoute: typeof CookiesRoute
  DiagnostikaRoute: typeof DiagnostikaRoute
  OfertaRoute: typeof OfertaRoute
  PolitikaRoute: typeof PolitikaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/politika': {
      id: '/politika'
      path: '/politika'
      fullPath: '/politika'
      preLoaderRoute: typeof PolitikaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oferta': {
      id: '/oferta'
      path: '/oferta'
      fullPath: '/oferta'
      preLoaderRoute: typeof OfertaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostika': {
      id: '/diagnostika'
      path: '/diagnostika'
      fullPath: '/diagnostika'
      preLoaderRoute: typeof DiagnostikaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CookiesRoute: CookiesRoute,
  DiagnostikaRoute: DiagnostikaRoute,
  OfertaRoute: OfertaRoute,
  PolitikaRoute: PolitikaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
