/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DiagnostikaRouteImport } from './routes/diagnostika'
import { Route as IndexRouteImport } from './routes/index'

const DiagnostikaRoute = DiagnostikaRouteImport.update({
  id: '/diagnostika',
  path: '/diagnostika',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diagnostika': typeof DiagnostikaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diagnostika': typeof DiagnostikaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diagnostika': typeof DiagnostikaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/diagnostika'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/diagnostika'
  id: '__root__' | '/' | '/diagnostika'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiagnostikaRoute: typeof DiagnostikaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/diagnostika': {
      id: '/diagnostika'
      path: '/diagnostika'
      fullPath: '/diagnostika'
      preLoaderRoute: typeof DiagnostikaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiagnostikaRoute: DiagnostikaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
